{% set name = "attrmap" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/attrmap-{{ version }}.tar.gz
  sha256: db2df4a2f737ebf246401680185b698b766a15cfb0379438217a4861bbc58c1a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  imports:
    - attrmap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yiqunchen1999/attrmap
  summary: An open source tool with **read-only protection** to help users get rid of dictionary in Python.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - YiqunChen1999
